### ISSUE TITLE
FEM 11th + 12th lecture

### ISSUE THREAD

**Issue by LostInDarkMath** [LostInDarkMath/MatheMaster#145]
will be teXed by: Henrik
will be reviewed by: Robert & Willi

**Comment by Mafaka1** [comment]
Es gibt nur noch eine Vorlesung pro Woche und die habe ich jetzt schon auf dem anderen branch commited

**Comment by LostInDarkMath** [comment]
Okay, gut zu wissen. 

Die Issues werden aber erst geschlossen, wenn der Code auf Master gemergt wird.
Also die Issues sollen den Stand auf master abbilden.

**Comment by Mafaka1** [comment]
Achso ok. Ich hab ebend wie gesagt auf den Mafaka1/FEM_fixes commited und warte auf ein review
Ich habe weiterhin deinen Rat befolgt und alles in eine figure umgebung getan

**Comment by Mafaka1** [comment]
Außerdem wusste ich nicht, dass ich mit "close and comment" den issue schließe:D

**Comment by Mafaka1** [comment]
Merged
