### ISSUE TITLE
Adopt a project license

### ISSUE THREAD

**Issue by phijor** [LostInDarkMath/MatheMaster#22]
We should [**really**](https://choosealicense.com/no-permission/) give this project a license. I would propose [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/). Debate me on the _non-commercial_ part.

**Comment by RobWalt** [comment]
What about [this](http://www.wtfpl.net/txt/copying/)? 😜

**Comment by phijor** [comment]
WTFPL is a software license, while CreativeCommons license are better suited for media other than software. I wouldn't classify TeX sources as software, therefore I think CC licenses would be preferable. There's always [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) if we want to go the route of _copy-left_.

Also, I'd like to keep stuff I contribute under proper licenses.

**Comment by RobWalt** [comment]
On a serious note, I think that your first suggestion would fit our purposes pretty well.

**Comment by LostInDarkMath** [comment]
I agree too.

**Comment by lugggas** [comment]
A word from me.

............. I don't care.
