### ISSUE TITLE
Hinzufügen von Hinweis bei Copyright Ansprüchen

### ISSUE THREAD

**Issue by RobWalt** [LostInDarkMath/MatheMaster#351]
Eine Professorin hat mich heute darauf hingewiesen, dass es besser wäre, wenn wir noch einen allgemeinen Hinweis für das repository erstellen.

Inhalt sollte die Möglichkeit sein, auf Anfrage ein Skript wieder zu entfernen, falls man aus Versehen Copyrights verletzt hat, wenn zum Beispiel die Vorlesung zu ähnlich zu einem Buch ist.

Bevor ich das einfach so mache, würde ich euch noch nach Input fragen. Ich werde das dann Ende der Woche in Angriff nehmen.

**Comment by LostInDarkMath** [comment]
Kannst du gern noch ergänzen. 

Ich glaube aber, dass es nicht notwendig ist, in die Output-PDFs mit reinzuschreiben, oder?

**Comment by RobWalt** [comment]
Ich würde es nur in die README Datei schreiben.
