### ISSUE TITLE
CI muss angepasst werden

### ISSUE THREAD

**Issue by RobWalt** [LostInDarkMath/MatheMaster#367]
@phijor Ich hab gerade in der .travis.yml gesehen, dass da einiges angepasst werden muss.
Reicht es, wenn man einfach die Daten auf 2019 setzt oder braucht es noch mehr? Ich sehe da nicht so ganz durch, sorry.

**Comment by RobWalt** [comment]
Ach egal, ich glaube das bekomm ich doch hin :D sag Bescheid, wenn was nicht stimmen sollte

**Comment by LostInDarkMath** [comment]
Gut, dass du dazu ein Issue öffnest. Hier noch Anliegen von mir:
- Ich schätze die automtischen Releases beim comitten eines Tags funktionieren aktuell nicht mehr, da wir vom "globalen" bin Order hin zu "lokalen" out Ordnern gewechselt sind in latexmk.
- Es wäre wünschenswert, wenn die CI auch Python und Pygmentize installiert hätte. Dann könnte man auch das Package MINTED benutzen.

**Comment by phijor** [comment]
Schaut mal in #384 rein.

**Comment by LostInDarkMath** [comment]
*PUSH*

Wir wollen Releases sehen! :)

**Comment by LostInDarkMath** [comment]
Haben wir ja eigentlich soweit. Die automatischen Releases wären zwar schön, aber kein Muss.
