### ISSUE TITLE
KONGEO: Bitte folgende Informationen ergänzen

### ISSUE THREAD

**Issue by LostInDarkMath** [LostInDarkMath/MatheMaster#369]
- dass es ein "Reading Course" ist
- Literatur
- dass es dementsprechend keine Mitschrift geben wird.

**Comment by lugggas** [comment]
https://www.tau.ac.il/~Borovoi/courses/ReprFG/Hatzagot.pdf

**Comment by LostInDarkMath** [comment]
Erledigt, siehe https://github.com/LostInDarkMath/MatheMaster/commit/77a1116cd5c3e22f01144248fece2fac6b3a6709
