### ISSUE TITLE
Rechtslage klären

### ISSUE THREAD

**Issue by LostInDarkMath** [LostInDarkMath/MatheMaster#376]
https://www.studentenwerk-dresden.de/soziales/rechtsberatung.html

**Comment by Hensto** [comment]
Wieso machst du hier ein Issue für sowas auf?

**Comment by LostInDarkMath** [comment]
Damit ich es nicht vergesse. Es haben sich meinerseits noch einige Fragen ergeben, die ich gern geklärt hätte, z.B. "Darf man Mitschriften einer Vorlesung hochladen, die strikt nach einem Buch gehalten wurde?" usw.

**Comment by LostInDarkMath** [comment]
Ist jetzt ein bisschen klarer...
