### ISSUE TITLE
Travis for automatic compilation missing

### ISSUE THREAD

**Issue by belamu** [LostInDarkMath/MatheMaster#531]
**Describe the bug**
The link to the released scripts only shows old scripts:
https://github.com/LostInDarkMath/MatheMaster/releases
It would be nice to have the current MSTAT lecture compiled.

**Expected behavior**
On the readme there is a link to up-to-date pdfs with a heading "Wintersemester 2019/20"

**Additional context**
Kommilitone fragte mich, was da los sei. Wisst ihr was da fehlt? @LostInDarkMath @RobWalt @phijor

**Comment by RobWalt** [comment]
Die Releases müssen im Moment noch manuell erzeugt werden. Es existiert dafür ein script, wenn ich mich nicht irre. Die aktuellen Releases sind einfach sehr veraltet

`` released ... on 15 Jul`` 😅

**Comment by belamu** [comment]
Ich hatte mich schon gewundert, dass github uns neben dem Speicherplatz auch noch erhebliche Rechenresourcen für das Kompilieren zur Verfügung stellt.
Ich sehe in dem skript `make-release.sh` nicht, wie das dann tatsächlich veröffentlicht wird. Es endet damit. dass man ein .tar.gz tarball hat. Wer kann releasen und wenn das jeder kann: wie?

**Comment by belamu** [comment]
Die lange Inaktivität erklärt auch, wie nicht aufgefallen ist, dass das make-release-skript nicht funktioniert, weil die latexmkrc in ANGALG seit der Umbenennung im August falsch, da nicht mitgeändert, ist.

**Comment by RobWalt** [comment]
achso, ich erinnere mich langsam wieder. Man muss einen Tag auf das repo pushen. Das geht mit

`git tag <tag_name>`
`git push origin <tag_name>`

Dann erkennt das travis irgendwie und erstellt den release. Bitte frag mich nicht wie das funktioniert, ich schätze, dass das mit in dem docker-image enthalten ist, welches @phijor ausgewählt hat.

**Comment by RobWalt** [comment]
Ah ja, in der travis-yml wird deploy nur getriggert, wenn man tags pusht. Ich hatte auch schonmal versucht das so einzurichten, dass es bei jedem change auf master neu releaset, bin aber daran gescheitert. Du kannst es ja gerne auch mal versuchen, wenn du magst oder eine gute Idee hast :smile:

**Comment by belamu** [comment]
Vielen Dank! Das habe ich jetzt auch hinbekommen. Ich denke mit dem Tags-pushen ist das schon eine gute Idee.
Einzige Kleinigkeit: die Überschrift bei dem Release passt noch nicht und ich finde auf Anhieb nicht, wo das eingestellt ist.

**Comment by belamu** [comment]
Und noch eine Sache: es gibt zwar die Ordner MSTAT_..18 und ..19, aber im Release nur das alte Skript. Ich vermute, die heißen halt gleich und dann wird nur eines genutzt.

**Comment by LostInDarkMath** [comment]
Also ich würde mir ja eigentlich **Continous Development (CD)** wünschen. Also das bei jedem Commit auf Master automatisch alle vorherigen Releases gelöscht werden und ein neues erzeugt wird.
